Categories = {
	--Politie--
	[23] = 'Noodhulp',
	[24] = 'Team Verkeer',
	[25] = 'Motor',
	[26] = 'Logistiek',
	[27] = 'Opleiding',
	[28] = 'Hondengeleider',
	[29] = 'Recherche',
	[30] = 'Noodhulp Onopvallend',
	[31] = 'LEEG',
	[32] = 'Overig',
	--BOA--
	[33] = 'Handhaving',
	[34] = 'Rijkswaterstraat',
	[35] = 'RET',
	[36] = 'Douane',
	----
	[37] = 'WIP',
	--KMAR--
	[38] = 'Politiedienst',
	[39] = 'HRB',
	[40] = 'Motor',
	[41] = 'Explosieven Opruimingsdienst Defensie',
	[42] = 'Officier van Dienst',
	[43] = 'Hondengeleider',
	[44] = 'Opleiding',
	[45] = 'Overig',
	[46] = 'Logistiek',
	--Brandweer--
	[47] = 'Dienstvoertuigen (DA/DB)',
	[48] = 'Waterongevallen (WO/BRV)', 
	[49] = 'Tankautospuiten (TS)',
	[50] = 'Tankautospuiten - Terreinvaardig (TST)',
	[51] = 'Redvoertuigen (AL/HW)',
	[52] = 'Schuimblusvoertuigen (SB/CT)',
	[53] = 'Hulpverleningsvoertuigen (HV)',
	[54] = 'Logistiek (LOG)',
	[55] = 'Officieren van Dienst (OvD)',
	[56] = 'Regionaal (AGS/TS/TBO)',
	--Onopvallend--
	[57] = 'NPC',
	[58] = 'Dienst Speciale Interventies',
	[59] = 'Overig',
	[60] = 'LEEG',
	[74] = 'LEEG',
	[75] = 'LEEG',
	--LEEG--
	[61] = 'LEEG',
	[62] = 'LEEG',
	[63] = 'LEEG',
	--Overig--
	[64] = 'Securitas',
	[65] = 'Rouwvervoer',
	[66] = 'Nieuws',
	[67] = 'PostNL',
	[68] = 'ProRail',
	[69] = 'Defensie',
	[70] = 'Koninklijk Huis',
	[71] = 'Development',
	[72] = 'DVO',
	[73] = 'Douane',
	--Ambulance--
	[76] = 'Rapid Responder',
	[77] = 'Officier van Dienst',
	[78] = 'Mobiel Medisch Team',
	[79] = 'Opleiding',
	[80] = 'Reguliere Ambulance',
	[81] = 'MICU',
	[82] = 'Orgaan Donatie',
	[83] = 'Coördinator',
	--Air support--
	[84] = 'Air Support',
	--OpCo / OvD Politie--
	[85] = 'OpCo/OvD',
	--SORT Ambu--
	[86] = 'SORT',
	--Politie Zeehavenpolitie--
	[87] = 'Zeehavenpolitie',
	--BOA V2--
	[88] = 'Overig',
	[89] = 'Handhaving Motor',
	[90] = 'Handhaving Unmarked',
	[91] = 'Handhaving Hi-ViZ',
	--KMAR V2--
	[92] = 'Air Support Unit',
	[93] = 'Kustwacht',
	[94] = 'Politiedienst in burger',
	--Burger--
	[100] = 'Tebex',
	[101] = 'Tweewieler',
	[102] = 'Trailer',
	[103] = 'Hatchback',
	[104] = 'Sedan',
	[105] = 'Station',
	[106] = 'Cabriolet',
	[107] = 'Coupe',
	[108] = 'Multi Purpose Vehicle', 
	[109] = 'Terrein',
	[110] = 'Commercieel',
	[111] = 'Watervoertuig',
	[112] = 'Luchtvoertuig',
   }

